server:
  port: 8080
spring:
  application:
    name: pos-graducao
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
      url: jdbc:h2:mem:contacts
      username: root
      password: root
      driver-class-name: org.h2.Driver